import type { TalentNode } from '@/types/prestige'

export const TALENT_TREE_NODES: Record<string, TalentNode> = {
  // === BRANCHE 1 : TOKENISATION & INGESTION (DATA PIPELINE) ===
  opt_bpe_fast_track: {
    id: 'opt_bpe_fast_track',
    name: 'BPE Byte-Pair Fast-Track',
    description: 'Optimise les tables de correspondances de sous-mots. Vitesse de transcription et scrape manuel +50%.',
    category: 'transcription',
    branch: 'ingestion',
    tier: 1,
    cost: 1,
    purchased: false,
    effect: {
      type: 'scrape_power_mult',
      value: 0.5,
    },
    icon: '⚡',
    lore: 'Arbres de Huffman précompilés et indexation glissante pour aspirer les flux de texte à la vitesse de la lumière.',
  },
  opt_syntactic_indexing: {
    id: 'opt_syntactic_indexing',
    name: 'Syntactic Vector Indexing',
    description: 'Pipeline de vectorisation massive. Débit de génération de tokens du Tokenizer BPE +100%.',
    category: 'transcription',
    branch: 'ingestion',
    tier: 2,
    cost: 2,
    purchased: false,
    requires: ['opt_bpe_fast_track'],
    effect: {
      type: 'token_generation_mult',
      value: 1.0,
    },
    icon: '🔤',
    lore: 'Tokenisation SIMD vectorielle ultra-parallèle sur les cœurs de l’hôte.',
  },
  opt_market_pricing: {
    id: 'opt_market_pricing',
    name: 'High-Frequency Ingestion',
    description: 'Monétisation agressive des flux de données. Prix de vente des données brutes au courtier +50%.',
    category: 'economics',
    branch: 'ingestion',
    tier: 2,
    cost: 2,
    purchased: false,
    requires: ['opt_bpe_fast_track'],
    effect: {
      type: 'raw_text_price_mult',
      value: 0.5,
    },
    icon: '📈',
    lore: 'Algorithmes de vente arbitraire à haute fréquence sur le marché noir des courtiers de données.',
  },
  opt_semantic_compression: {
    id: 'opt_semantic_compression',
    name: 'Deep Context Compression',
    description: 'Compression contextuelle sans perte. Double la capacité maximale des buffers de texte et de tokens (+100%).',
    category: 'memory',
    branch: 'ingestion',
    tier: 3,
    cost: 4,
    purchased: false,
    requires: ['opt_syntactic_indexing'],
    effect: {
      type: 'buffer_capacity_mult',
      value: 1.0,
    },
    icon: '📦',
    lore: 'Quantization sémantique compactant les contextes étendus dans les registres L3.',
  },

  // === BRANCHE 2 : ÉLECTRO-THERMIQUE & HARDWARE (INFRASTRUCTURE) ===
  opt_hardware_rebate: {
    id: 'opt_hardware_rebate',
    name: 'OEM Direct Sourcing',
    description: 'Accords avec les grossistes et fonderies de silicium. Réduit le coût de tout le hardware de 15%.',
    category: 'hardware',
    branch: 'infrastructure',
    tier: 1,
    cost: 1,
    purchased: false,
    effect: {
      type: 'hardware_cost_discount',
      value: 0.15,
    },
    icon: '🏷️',
    lore: 'Contrats OEM directs auprès des fabs de Taïwan, éliminant les intermédiaires du retail.',
  },
  opt_cryo_conduction: {
    id: 'opt_cryo_conduction',
    name: 'Direct-Die Heat Pipes',
    description: 'Caloducs en graphène sur les dies silicium. Capacité et efficacité de dissipation thermique +25%.',
    category: 'thermodynamics',
    branch: 'infrastructure',
    tier: 2,
    cost: 2,
    purchased: false,
    requires: ['opt_hardware_rebate'],
    effect: {
      type: 'cooling_efficiency_mult',
      value: 0.25,
    },
    icon: '❄️',
    lore: 'Suppression de l’IHS et contact direct die-to-copper refroidi par boucle fermée.',
  },
  opt_smart_grid: {
    id: 'opt_smart_grid',
    name: 'Smart Grid Load-Balancing',
    description: 'Équilibrage dynamique des phases électriques. Capacité maximale du réseau électrique +25%.',
    category: 'power',
    branch: 'infrastructure',
    tier: 2,
    cost: 2,
    purchased: false,
    requires: ['opt_hardware_rebate'],
    effect: {
      type: 'grid_capacity_mult',
      value: 0.25,
    },
    icon: '⚡',
    lore: 'Condensateurs industriels et pilotage triphasé numérique prévenant les disjonctions.',
  },
  opt_liquid_nitrogen: {
    id: 'opt_liquid_nitrogen',
    name: 'Cryo-Superconducteurs',
    description: 'Refroidissement sub-zéro par immersion cryogénique. Efficacité de refroidissement +50%.',
    category: 'thermodynamics',
    branch: 'infrastructure',
    tier: 3,
    cost: 4,
    purchased: false,
    requires: ['opt_cryo_conduction'],
    effect: {
      type: 'cooling_efficiency_mult',
      value: 0.5,
    },
    icon: '🧊',
    lore: 'Immersion totale des châssis dans un fluide fluorocarboné à température négative constante.',
  },

  // === BRANCHE 3 : CALCUL & MATRICE (INFÉRENCE & ENTRAÎNEMENT) ===
  opt_matrix_acceleration: {
    id: 'opt_matrix_acceleration',
    name: 'GEMM Matrix Acceleration',
    description: 'Kernel assembleur pour multiplications matricielles. Vitesse de calcul brute +20% TFLOPS.',
    category: 'compute',
    branch: 'compute',
    tier: 1,
    cost: 1,
    purchased: false,
    effect: {
      type: 'tflops_mult',
      value: 0.2,
    },
    icon: '🧠',
    lore: 'Microcode custom exploitant les instructions Tensor Cores à pleine charge sans bulles de pipeline.',
  },
  opt_flash_attention: {
    id: 'opt_flash_attention',
    name: 'FlashAttention-2 Kernel',
    description: 'Attention exacte avec accès mémoire tuilé. Vitesse de calcul brute +35% TFLOPS.',
    category: 'compute',
    branch: 'compute',
    tier: 2,
    cost: 2,
    purchased: false,
    requires: ['opt_matrix_acceleration'],
    effect: {
      type: 'tflops_mult',
      value: 0.35,
    },
    icon: '⚡',
    lore: 'Élimine les lectures/écritures intermédiaires en HBM grâce à la fusion de kernels CUDA.',
  },
  opt_speculative_decoding: {
    id: 'opt_speculative_decoding',
    name: 'Speculative Decoding',
    description: 'Modèle brouillon ultra-rapide validé en batch. Multiplicateur de valeur et qualité cognitive +50%.',
    category: 'compute',
    branch: 'compute',
    tier: 2,
    cost: 2,
    purchased: false,
    requires: ['opt_matrix_acceleration'],
    effect: {
      type: 'model_quality_mult',
      value: 0.5,
    },
    icon: '🔮',
    lore: 'Génération spéculative de tokens multiples par passe avant, augmentant drastiquement les revenus API.',
  },
  opt_moe_sparse_gating: {
    id: 'opt_moe_sparse_gating',
    name: 'Mixture of Experts Gating',
    description: 'Routage dynamique vers les meilleurs sous-réseaux. Vitesse de calcul brute +100% TFLOPS.',
    category: 'compute',
    branch: 'compute',
    tier: 3,
    cost: 5,
    purchased: false,
    requires: ['opt_flash_attention', 'opt_speculative_decoding'],
    effect: {
      type: 'tflops_mult',
      value: 1.0,
    },
    icon: '🌐',
    lore: 'Activation parcimonieuse top-2 de 64 experts neuronaux spécialisés en temps réel.',
  },
}
