import Decimal from 'break_infinity.js'
import type { SoftwareUpgrade } from '@/types/upgrades'

export const INITIAL_UPGRADES_CONFIG: Record<string, SoftwareUpgrade> = {
  // Phase 0 : Human Reading Skills
  human_speed_reading: {
    id: 'human_speed_reading',
    name: 'Technique de Lecture Rapide',
    description: 'Balayage visuel des paragraphes : lecture manuelle portée à 15 caractères par action (+50%).',
    cost: new Decimal(0.15),
    currency: 'funds',
    purchased: false,
    category: 'human',
  },
  human_espresso: {
    id: 'human_espresso',
    name: 'Double Tasse d’Espresso',
    description: 'Pic de caféine et concentration accrue : lecture manuelle portée à 25 caractères par action.',
    cost: new Decimal(0.60),
    currency: 'funds',
    purchased: false,
    category: 'human',
  },
  broker_negotiation: {
    id: 'broker_negotiation',
    name: 'Négociation Courtier de Données',
    description: 'Revalorise le tarif des données brutes ($0.08 les 20 caractères au lieu de $0.05).',
    cost: new Decimal(2.50),
    currency: 'funds',
    purchased: false,
    category: 'monetization',
    requiredFeature: 'dataBroker',
  },

  // Phase 1 : Potato PC Scripts & Early Memory
  script_simple_scraper: {
    id: 'script_simple_scraper',
    name: 'Script simple_scraper.py',
    description: "Script Python tournant en tâche de fond sur le PC (+5 chars/s d'auto-scraping passif).",
    cost: new Decimal(3.00),
    currency: 'funds',
    purchased: false,
    category: 'scraping',
    requiredFeature: 'scriptsSection',
  },
  ram_sdram_256mb: {
    id: 'ram_sdram_256mb',
    name: 'Barrette 256 Mo SDRAM Récupérée',
    description: 'Étend la mémoire vive du vieux PC : capacité Raw Text portée à 1 500 caractères.',
    cost: new Decimal(4.50),
    currency: 'funds',
    purchased: false,
    category: 'hardware',
    requiredFeature: 'scriptsSection',
  },
  script_cron_autobroker: {
    id: 'script_cron_autobroker',
    name: 'Cron auto_broker.py',
    description: 'Vente automatique au courtier dès que 40 caractères sont accumulés (aucun clic requis).',
    cost: new Decimal(5.00),
    currency: 'funds',
    purchased: false,
    category: 'monetization',
    requiredFeature: 'scriptsSection',
  },
  script_regex_cleaner: {
    id: 'script_regex_cleaner',
    name: 'Parser clean_html_regex.py',
    description: 'Nettoie les balises HTML : +10 chars/s en auto et +15 chars par lecture manuelle.',
    cost: new Decimal(7.50),
    currency: 'funds',
    purchased: false,
    category: 'scraping',
    requiredFeature: 'scriptsSection',
  },
  script_ram_expansion_512: {
    id: 'script_ram_expansion_512',
    name: 'Patch Swap swap_ram.sh',
    description: 'Étend la mémoire tampon virtuelle : capacité de Raw Text portée à 2 500 caractères.',
    cost: new Decimal(10.00),
    currency: 'funds',
    purchased: false,
    category: 'hardware',
    requiredFeature: 'scriptsSection',
  },
  script_multi_curl: {
    id: 'script_multi_curl',
    name: 'Daemon multi_curl.py',
    description: 'Aspiration multi-connexions en parallèle (+20 chars/s supplémentaires).',
    cost: new Decimal(15.00),
    currency: 'funds',
    purchased: false,
    category: 'scraping',
    requiredFeature: 'scriptsSection',
  },
  power_psu_500w: {
    id: 'power_psu_500w',
    name: 'Bloc d’Alimentation 500W Bronze Modulaire',
    description: 'Alimentation 80+ Bronze modulaire remplaçant le vieux bloc d’origine (+400W de capacité réseau).',
    cost: new Decimal(25.00),
    currency: 'funds',
    purchased: false,
    category: 'power',
    requiredFeature: 'scriptsSection',
  },

  // Phase 2 : Workstation & Tokenizer RAM Kits
  ram_ddr2_8gb: {
    id: 'ram_ddr2_8gb',
    name: 'Kit 8 Go DDR2-800 Dual-Channel',
    description: 'Double la RAM système : capacité Raw Text à 6 000 chars et Tokens à 3 000 $T$.',
    cost: new Decimal(14.00),
    currency: 'funds',
    purchased: false,
    category: 'hardware',
    requiredFeature: 'tokenizerUnlocked',
  },
  ram_ddr3_16gb: {
    id: 'ram_ddr3_16gb',
    name: 'Kit 16 Go DDR3/DDR4 d\'Occasion',
    description: 'Capacité Raw Text portée à 15 000 chars et Tokens à 8 000 $T$.',
    cost: new Decimal(28.00),
    currency: 'funds',
    purchased: false,
    category: 'hardware',
    requiredFeature: 'tokenizerUnlocked',
  },
  ram_ddr4_32gb: {
    id: 'ram_ddr4_32gb',
    name: 'Kit 32 Go DDR4-3200 Dual-Rank',
    description: 'Capacité Raw Text portée à 40 000 chars et Tokens à 25 000 $T$.',
    cost: new Decimal(65.00),
    currency: 'funds',
    purchased: false,
    category: 'hardware',
    requiredFeature: 'tokenizerUnlocked',
  },
  fast_bpe_tokenizer: {
    id: 'fast_bpe_tokenizer',
    name: 'BPE Tokenizer Vectorisé',
    description: 'Optimise la vectorisation BPE en mémoire, doublant la vitesse de tokenisation automatique.',
    cost: new Decimal(75.00),
    currency: 'funds',
    purchased: false,
    category: 'tokenizer',
    requiredFeature: 'tokenizerUnlocked',
  },
  // Active Cooling Solutions
  cooling_case_fans_120mm: {
    id: 'cooling_case_fans_120mm',
    name: 'Ventilateurs Boîtier 120mm (x2)',
    description: 'Deux ventilateurs 120mm à 2 000 RPM pour extraire l’air chaud (+70W de dissipation).',
    cost: new Decimal(18.00),
    currency: 'funds',
    purchased: false,
    category: 'cooling',
    requiredFeature: 'scriptsSection',
  },
  cooling_tower_heatsink: {
    id: 'cooling_tower_heatsink',
    name: 'Ventirad Cuivre Double Tour Noctua',
    description: 'Dissipateur à caloducs en cuivre massif et double ventilateur 140mm silencieux (+180W de dissipation).',
    cost: new Decimal(55.00),
    currency: 'funds',
    purchased: false,
    category: 'cooling',
    requiredFeature: 'tokenizerUnlocked',
  },
  cooling_optimization_v1: {
    id: 'cooling_optimization_v1',
    name: 'Dissipateur Cuivre Haut Débit',
    description: 'Améliore la dissipation thermique passive (+200W de Cooling Capacity).',
    cost: new Decimal(120.00),
    currency: 'funds',
    purchased: false,
    category: 'cooling',
    requiredFeature: 'tokenizerUnlocked',
  },
  cooling_aio_watercooling_360: {
    id: 'cooling_aio_watercooling_360',
    name: 'Kit Watercooling AIO 360mm Triple Fan',
    description: 'Circuit liquide scellé avec radiateur aluminium 360mm pour refroidir les GPU RTX (+450W de dissipation).',
    cost: new Decimal(160.00),
    currency: 'funds',
    purchased: false,
    category: 'cooling',
    requiredFeature: 'tokenizerUnlocked',
  },
  ram_ddr4_64gb: {
    id: 'ram_ddr4_64gb',
    name: 'Kit 64 Go DDR4-3600 High-Speed',
    description: 'Capacité Raw Text portée à 100 000 chars et Tokens à 75 000 $T$.',
    cost: new Decimal(140.00),
    currency: 'funds',
    purchased: false,
    category: 'hardware',
    requiredFeature: 'tokenizerUnlocked',
  },
  api_tier_pricing: {
    id: 'api_tier_pricing',
    name: 'Pricing API Tier Pro',
    description: "Augmente le tarif de base par token d'inférence servi ($0.10 au lieu de $0.05 par token).",
    cost: new Decimal(200.00),
    currency: 'funds',
    purchased: false,
    category: 'monetization',
    requiredFeature: 'tokenizerUnlocked',
  },
  crawler_daemon_v2: {
    id: 'crawler_daemon_v2',
    name: 'Cluster Crawler Parallèle v2.0',
    description: "Distribue le scraping web à grande échelle (+60 chars/s d'auto-scraping).",
    cost: new Decimal(350.00),
    currency: 'funds',
    purchased: false,
    category: 'scraping',
    requiredFeature: 'tokenizerUnlocked',
  },
  power_psu_850w_gold: {
    id: 'power_psu_850w_gold',
    name: 'Bloc d’Alimentation 850W Gold Multi-Rail',
    description: 'Alimentation haute performance 80+ Gold à double rail 12V (+750W de capacité réseau).',
    cost: new Decimal(75.00),
    currency: 'funds',
    purchased: false,
    category: 'power',
    requiredFeature: 'tokenizerUnlocked',
  },
  power_dedicated_circuit_16a: {
    id: 'power_dedicated_circuit_16a',
    name: 'Ligne Dédiée Disjoncteur 16A Tableau',
    description: 'Tirage d’un câble 2.5 mm² blindé avec disjoncteur 16A dédié pour éviter les coupures (+2 500W de capacité réseau).',
    cost: new Decimal(280.00),
    currency: 'funds',
    purchased: false,
    category: 'power',
    requiredFeature: 'tokenizerUnlocked',
  },

  // Phase 3 : Training & Datacenter Memory & High-End Cooling
  cooling_custom_loop_d5: {
    id: 'cooling_custom_loop_d5',
    name: 'Boucle Watercooling Custom Cuivre & Pompe D5',
    description: 'Circuit sur-mesure à tubage rigide, réservoir 250ml et radiateur 480mm multi-GPU (+1 200W de dissipation).',
    cost: new Decimal(500.00),
    currency: 'funds',
    purchased: false,
    category: 'cooling',
    requiredFeature: 'trainingAllocation',
  },
  cooling_inrow_datacenter_ac: {
    id: 'cooling_inrow_datacenter_ac',
    name: 'Climatisation In-Row Salle Serveur 4U',
    description: 'Unité industrielle en baie soufflant de l’air réfrigéré à 16°C pour refroidir les baies denses (+4 000W de dissipation).',
    cost: new Decimal(2500.00),
    currency: 'funds',
    purchased: false,
    category: 'cooling',
    requiredFeature: 'trainingAllocation',
  },
  cooling_immersion_cryo: {
    id: 'cooling_immersion_cryo',
    name: 'Cuve d’Immersion Diélectrique Cryogénique',
    description: 'Bain d’huile diélectrique biphasique à évaporation sous vide pour clusters de puces H100 (+15 000W de dissipation).',
    cost: new Decimal(12000.00),
    currency: 'funds',
    purchased: false,
    category: 'cooling',
    requiredFeature: 'trainingAllocation',
  },
  power_triphase_industrial: {
    id: 'power_triphase_industrial',
    name: 'Branchement Triphasé Industriel 400V 32A',
    description: 'Raccordement réseau triphasé moyenne tension pour alimenter des racks multi-GPU sans saturation (+8 000W de capacité réseau).',
    cost: new Decimal(1200.00),
    currency: 'funds',
    purchased: false,
    category: 'power',
    requiredFeature: 'trainingAllocation',
  },
  power_substation_transformer: {
    id: 'power_substation_transformer',
    name: 'Poste Haute Tension & Transformateur Dédié 50 kVA',
    description: 'Transformateur d’infrastructure sous cabine étanche pour alimenter des clusters de supercalculateurs (+35 000W de capacité réseau).',
    cost: new Decimal(8500.00),
    currency: 'funds',
    purchased: false,
    category: 'power',
    requiredFeature: 'trainingAllocation',
  },
  ram_ddr5_128gb: {
    id: 'ram_ddr5_128gb',
    name: 'Kit 128 Go DDR5-6000 EXPO',
    description: 'Capacité Raw Text portée à 300 000 chars et Tokens à 250 000 $T$.',
    cost: new Decimal(380.00),
    currency: 'funds',
    purchased: false,
    category: 'hardware',
    requiredFeature: 'trainingAllocation',
  },
  ram_ddr5_256gb: {
    id: 'ram_ddr5_256gb',
    name: 'Kit 256 Go DDR5 Octo-Channel ECC',
    description: 'Capacité Raw Text portée à 1 000 000 chars et Tokens à 1 000 000 $T$.',
    cost: new Decimal(850.00),
    currency: 'funds',
    purchased: false,
    category: 'hardware',
    requiredFeature: 'trainingAllocation',
  },

  // Phase 3 : AI Safety & Cognitive Upgrades
  safety_constitutional_ai: {
    id: 'safety_constitutional_ai',
    name: 'Constitutional AI Ruleset',
    description: 'Intègre des principes éthiques stricts dans la loss function d’entraînement (-20% de dérive d’entropie).',
    cost: new Decimal(300.00),
    currency: 'funds',
    purchased: false,
    category: 'security',
    requiredFeature: 'trainingAllocation',
  },
  safety_automated_rlhf: {
    id: 'safety_automated_rlhf',
    name: 'Pipeline Automated RLHF',
    description: 'Déploie des modèles de récompense automatisés pour dissiper passivement l’entropie (-0.5% entropie/s).',
    cost: new Decimal(750.00),
    currency: 'funds',
    purchased: false,
    category: 'security',
    requiredFeature: 'trainingAllocation',
  },
  safety_dpo_optimization: {
    id: 'safety_dpo_optimization',
    name: 'Direct Preference Optimization (DPO)',
    description: 'Optimisation directe des préférences sans réseau de récompense séparé (-30% de dérive d’entropie supplémentaire).',
    cost: new Decimal(1500.00),
    currency: 'funds',
    purchased: false,
    category: 'security',
    requiredFeature: 'trainingAllocation',
  },
  safety_benchmarks: {
    id: 'safety_benchmarks',
    name: 'Automated Safety Benchmarks',
    description: 'Bancs d’évaluation continus garantissant un plancher de factualité : plafonne le malus d’hallucination API à -20% max.',
    cost: new Decimal(3000.00),
    currency: 'funds',
    purchased: false,
    category: 'security',
    requiredFeature: 'trainingAllocation',
  },
  safety_rlaif: {
    id: 'safety_rlaif',
    name: 'RLAIF (AI Feedback Alignment)',
    description: 'Alignement par retour d’IA : repousse le seuil de Model Collapse à 85% et réduit la dérive synthétique de 40%.',
    cost: new Decimal(10000.00),
    currency: 'funds',
    purchased: false,
    category: 'security',
    requiredFeature: 'trainingAllocation',
  },
  safety_syntactic_diversity: {
    id: 'safety_syntactic_diversity',
    name: 'Syntactic Diversity Evaluator',
    description: 'Évaluateur de diversité syntaxique : annule totalement le malus d’entraînement (-50%) lors d’un Model Collapse.',
    cost: new Decimal(50000.00),
    currency: 'funds',
    purchased: false,
    category: 'security',
    requiredFeature: 'trainingAllocation',
  },
  safety_synthetic_density_filter: {
    id: 'safety_synthetic_density_filter',
    name: 'Synthetic Density Filter',
    description: 'Filtre de densité sémantique avancé : immunise totalement le modèle contre le Model Collapse (100% données synthétiques sécurisées).',
    cost: new Decimal(250000.00),
    currency: 'funds',
    purchased: false,
    category: 'security',
    requiredFeature: 'trainingAllocation',
  },
}

export function createInitialUpgrades(): Record<string, SoftwareUpgrade> {
  const cloned: Record<string, SoftwareUpgrade> = {}
  for (const [key, up] of Object.entries(INITIAL_UPGRADES_CONFIG)) {
    cloned[key] = {
      id: up.id,
      name: up.name,
      description: up.description,
      cost: new Decimal(up.cost),
      currency: up.currency,
      purchased: up.purchased,
      category: up.category,
      requiredFeature: up.requiredFeature,
    }
  }
  return cloned
}
